# ProBot Request Info (https://probot.github.io/apps/request-info/)

requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/pr!

requestInfoLabelToAdd: needs-more-info

# ProBot Welcome (https://probot.github.io/apps/welcome/)

newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!

newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

firstPRMergeComment: >
  ![congrats](https://media1.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

  Congrats on your very first contribution :clap: Looking forward to having more from your side
