name: CI
on:
  push:
  pull_request:
    branches:
      - master
      - next
  workflow_dispatch:
jobs:
  job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node: ['12', '14']
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Install packages
      run: npm ci
    - name: Run e2e tests
      run: npm run test
